version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
    mem_limit: 2g # Если ты добавил ограничение памяти, оставь его

  app:
    build: ./app
    ports:
      - "8000:8000"
    depends_on:
      - jenkins

volumes:
  jenkins-data:
