http:
  routers:
    jenkins:
      rule: "Host(`a.example.com`)"
      entrypoints:
        - websecure
      service: jenkins
      tls: {}
  services:
    jenkins:
      loadBalancer:
        servers:
          - url: "http://jenkins:8080"
